# æµ‹è¯•é…ç½®æ–‡ä»¶
# @author NanoDa Team
# @from ç¼–ç¨‹å¯¼èˆªçŸ¥è¯†æ˜Ÿçƒ
server:
  port: 8101
spring:
  # æ•°æ®åº“é…ç½?  # todo éœ€æ›¿æ¢é…ç½®
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 123456
  # Redis é…ç½®
  # todo éœ€æ›¿æ¢é…ç½®
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  # Elasticsearch é…ç½®
  # todo éœ€æ›¿æ¢é…ç½®
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456



